import datetime
from typing import TYPE_CHECKING, overload

from disgrace import ids
from disgrace.abc import Snowflake
from disgrace.structs import raw_ids
from disgrace.utils import snowflake_time


@property
def created_at(self: Snowflake[ids.SnowflakeId]) -> datetime.datetime:
    return snowflake_time(self.id)


# lgtm 👍
if TYPE_CHECKING:

    @overload
    def cast_int_id(id: raw_ids.ChannelId, /) -> ids.ChannelId: ...
    @overload
    def cast_int_id(id: raw_ids.GuildId, /) -> ids.GuildId: ...
    @overload
    def cast_int_id(id: raw_ids.SkuId, /) -> ids.SkuId: ...
    @overload
    def cast_int_id(id: raw_ids.UserId, /) -> ids.UserId: ...
    @overload
    def cast_int_id(id: raw_ids.GuildEmojiId, /) -> ids.GuildEmojiId: ...
    @overload
    def cast_int_id(id: raw_ids.AppEmojiId, /) -> ids.AppEmojiId: ...
    @overload
    def cast_int_id(id: raw_ids.RoleId, /) -> ids.RoleId: ...
    @overload
    def cast_int_id(id: raw_ids.MessageId, /) -> ids.MessageId: ...
    @overload
    def cast_int_id(id: raw_ids.WebhookId, /) -> ids.WebhookId: ...
    @overload
    def cast_int_id(id: raw_ids.ApplicationId, /) -> ids.ApplicationId: ...
    @overload
    def cast_int_id(id: raw_ids.StickerId, /) -> ids.StickerId: ...
    @overload
    def cast_int_id(id: raw_ids.StickerPackId, /) -> ids.StickerPackId: ...
    @overload
    def cast_int_id(id: raw_ids.AttachmentId, /) -> ids.AttachmentId: ...

    @overload
    def cast_str_id(id: ids.ChannelId, /) -> raw_ids.ChannelId: ...
    @overload
    def cast_str_id(id: ids.GuildId, /) -> raw_ids.GuildId: ...
    @overload
    def cast_str_id(id: ids.SkuId, /) -> raw_ids.SkuId: ...
    @overload
    def cast_str_id(id: ids.UserId, /) -> raw_ids.UserId: ...
    @overload
    def cast_str_id(id: ids.GuildEmojiId, /) -> raw_ids.GuildEmojiId: ...
    @overload
    def cast_str_id(id: ids.AppEmojiId, /) -> raw_ids.AppEmojiId: ...
    @overload
    def cast_str_id(id: ids.RoleId, /) -> raw_ids.RoleId: ...
    @overload
    def cast_str_id(id: ids.MessageId, /) -> raw_ids.MessageId: ...
    @overload
    def cast_str_id(id: ids.WebhookId, /) -> raw_ids.WebhookId: ...
    @overload
    def cast_str_id(id: ids.ApplicationId, /) -> raw_ids.ApplicationId: ...
    @overload
    def cast_str_id(id: ids.StickerId, /) -> raw_ids.StickerId: ...
    @overload
    def cast_str_id(id: ids.StickerPackId, /) -> raw_ids.StickerPackId: ...
    @overload
    def cast_str_id(id: ids.AttachmentId, /) -> raw_ids.AttachmentId: ...


def cast_int_id(id: raw_ids.SnowflakeId, /) -> ids.SnowflakeId:
    return ids.SnowflakeId(int(id))


def cast_str_id(id: ids.SnowflakeId, /) -> raw_ids.SnowflakeId:
    return raw_ids.SnowflakeId(str(id))
